### ISSUE TITLE
Add device DNA to a register

### ISSUE THREAD

**Issue by andrewpeck** [cms-gem-daq-project/OptoHybridv3#10]

**Comment by lpetre-ulb** [comment]
Is this issue still relevant ? I have some time to create a "module" if it is still needed.

**Comment by andrewpeck** [comment]
Ah, no, I have a Device DNA module now https://github.com/andrewpeck/OptoHybridv3/blob/devel/src/control/device_dna.v

It supports Virtex-6 and Artix-7 but is not yet in the main branch of the firmware.

**Comment by lpetre-ulb** [comment]
Ok, thanks.
