### ISSUE TITLE
Release name standartization

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/OptoHybridv3#11]
We need the OH releases to have standard names with the difference only in release tag.
We can't retrieve automatically the names containing dates
@andrewpeck @bdorney

**Comment by bdorney** [comment]
Yeah so the proposed convention is:

```
OH_20180215_3.0.10.A.tar.gz
```

OH_3.X.Y.C.tar.gz

Where `X` and `Y` are integers and `C` is a character, e.g. {`A`,`B`,`C`}.

In this convention could the following three releases have their `*.tar.gz` file re-uploaded:

- https://github.com/cms-gem-daq-project/OptoHybridv3/releases/tag/3.0.10.A
- https://github.com/cms-gem-daq-project/OptoHybridv3/releases/tag/3.1.0.B
- https://github.com/cms-gem-daq-project/OptoHybridv3/releases/tag/3.1.1.B

This would then let us to script the checkout and setup of an OH FW file, address table, and required `lmdb` updates.  This is necessary the first time a CTP7 is setup and each time the FW is updated.

See: https://github.com/cms-gem-daq-project/gemctp7user/issues/21

@andrewpeck @mexanick

**Comment by andrewpeck** [comment]
Okay, will do.

Should the file names also match this scheme: i.e.

OH-20180320-3.1.1.B.bit
OH-20180320-3.1.1.B.cdc
OH-20180320-3.1.1.B.cfi
OH-20180320-3.1.1.B.mcs
OH-20180320-3.1.1.B.prm
optohybrid_registers.xml


should change to

OH-3.1.1.B.bit
OH-3.1.1.B.cdc
OH-3.1.1.B.cfi
OH-3.1.1.B.mcs
OH-3.1.1.B.prm
optohybrid_registers.xml

Or do you have another preferred name?   All these files and tarballs are
generated by tcl script so it is easy for me to do whatever scheme you
desire...

Would a versioned naming scheme for the xml file work also?

e.g. OH-3.1.1.B.xml or OH-Registers-3.1.1.B.xml etc....

Thanks,

Andrew

**Comment by mexanick** [comment]
please make sure, that you use either dash ("-") or underscore ("_") everywhere in the names. So far you are mixing both

**Comment by andrewpeck** [comment]
Hi all,

Thanks for the feedback!

One further question:

We will have the first prototypes of GE2/1 firmware soon (actually, next
week will be the first version with preliminary pinouts by Mike).. we
should think about how to unify the naming scheme between the two systems.

For example:

oh_ge11_3.1.1.B.bit
vs.
oh_ge21_3.1.1.B.bit

What do you think?

Thanks,

Andrew

**Comment by mexanick** [comment]
Why don't use the existing version numbers for that? For example we can reserve 3.X.Y for the GE1/1 and use e.g. 4.X.Y for GE2/1

**Comment by bdorney** [comment]
> Why don't use the existing version numbers for that? For example we can reserve 3.X.Y for the GE1/1 and use e.g. 4.X.Y for GE2/1

I don't see anything wrong with this proposal as long as it is documented thoroughly (e.g. in the `README.md` of the repo as is presently).

Howevere there will be 2-4 different types of OH's for GE2/1.  Additionally there will be 8 readout boards for GE2/1 with most likely a similar number of GEBs.  This will require a different set of timing tap registers and SOT delay registers for each setup.  Will each of these boards have the same firmware...?  Given that we were discussing hard coding firmware settings for each detector/OH pairing for GE1/1 I suspect no...?  

Here the versioning system may fail and we will need to come up with an alternative convention. 
 @andrewpeck any info on the above comments? Was a decision on the number of OH's taken as of yet?

Finally there is also the OH for ME0 to consider.

**Comment by mexanick** [comment]
I think we should go in the direction of maintaining versioning in the release number. If we do not have enough digits in a current release format, we can add more... However given the we have already 4 digits, where first defines hardware generation, we than have two other for the changelog and we can have last one to indicate on which type of OH given FW should reside... So I don't really see the problems with using existing version numbering scheme

**Comment by jsturdy** [comment]
Probably best to not try to reinvent the wheel...

https://semver.org/

**Comment by jsturdy** [comment]
On the other hand, the AMC13 guys eschewed semantic versioning in favour
of their style, where they have different support versions each
containing some base level of functionality, effectively a HW type
coupled with a release ID
See the top of:
http://ohm.bu.edu/~dzou/firmware.cgi

This type of versioning probably makes more sense in the
hardware/firmware world, as it more accurately describes what the
versions are doing, while in software, the semantic versioning model is
probably more descriptive.

**Comment by mexanick** [comment]
I totally agree. I just don't want to have something like this:
OH_X.Y.Z.A_oh-my-very-special-release-which-works-only-when-unicorns-are-running-it.zip
We can follow the regular semantics for X.Y.Z. and leave "A" for specification of the board (as we actually do right now)

**Comment by andrewpeck** [comment]
Yup, they are all in the tar. thanks :)
