### ISSUE TITLE
Tag 3.1.5.1C on master branch

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/OptoHybridv3#13]
While rebasing the ULB TDC on the master branch, I noticed that the tag 3.1.5.1C (commit 6457816) was not pushed on master branch (currently commit 5b2160b).

Is it the expected behavior ? On which commit should I rebase the TDC to be up to date ?

**Comment by lpetre-ulb** [comment]
Thank you for this information. I had already seen that you use git-flow for SW development, but the guide seems more complete.

For the FW development, I do not see any `develop` branch. However, the TDC is obviously in a new branch considering it is a brand new feature.

**Comment by andrewpeck** [comment]
I'm not sure I'm following the problem but https://github.com/cms-gem-daq-project/OptoHybridv3/commit/645781627ffa1059952abb5c3c17d843b68eea13 is the most recent commit that you should trust. 

I have a whole other slurry of things going on with GE2/1 firmware that will need to be merged in eventually, but at the moment it is a lot better to just stick with 645781627ffa1059952abb5c3c17d843b68eea13

I'm not sure about the manifesto either--the firmware hasn't really been very collaborative up until this point (just one person working at a time) so I haven't had to worry about much in the way of manifestos :/

I have a development branch in my fork that I'm building new features on but I wouldn't recommend touching it any time soon.. it is a big change from the current firmware to support GE2/1 and its not backwards compatible on the CTP7

**Comment by lpetre-ulb** [comment]
Thank you for your complete answer, I'll then rebase on commit 6457816.

When I opened the issue, commit 6457816 was not present on master, though the tag 3.1.5.1C referred to it. It is now the HEAD on master, so the issue can be considered closed.
