### ISSUE TITLE
HDMI mode/sel question

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/OptoHybridv3#16]
@andrewpeck do I read correctly from the documentation that there are 8 HDMI s-bit output mode and 8 HDMI s-bit output select settings?
Previously `mode` was common, and `sel` would be chosen based on the `mode`, however if I understand correctly, I can now configure the HDMI output to have each of the 8 signals independently, i.e., signal 1 could be a specific VFAT, while signal 2 could be the `iEta` row containing that VFAT.
Can you confirm if this is correct (and desired @bdorney)?

**Comment by andrewpeck** [comment]
Hi Jared, 

Yes there are registers for SEL[7:0] and MODE[7:0] and they are independently controlled for each bit. 

I don't know if it is necessary, but it was easy to implement and seemed to offer more flexibility. 

It could be removed if desired but it seems easy enough to just write the mode to all be the same if you want them all the same? 

Just let me know hwat you prefer.
