### ISSUE TITLE
Add error correction on trigger links

### ISSUE THREAD

**Issue by andrewpeck** [cms-gem-daq-project/OptoHybridv3#18]

**Comment by lpetre-ulb** [comment]
Hi Andrew,

I don't know if you already started working on this issue, but I just though that the GBT protocol could be used for this purpose. It provides the required functionalities and bandwidth and is optimized for low latency. Moreover the optical path should also already be ready. 

Or maybe is it completely overkill and you were thinking about something simpler? Also can the CTP7 support 24 additional GBT RX cores?

**Comment by andrewpeck** [comment]
Hi Laurent,  Evaldas and I actually had the same idea. It would work very well on GE2/1 where we can run at 4.8 Gbps but the complication is that the Virtex-6 for GE1/1 only supports a line rate of 4.0 Gbps because of the reference clock limitation -- (off the top of my head I think we need 120 MHz refclk to get to 4.8). So if we did want to use a GBTX core it would have to be customized in some perhaps non-trivial way.. 

It is still something to look into but is not as simple as we had hoped at first :( 

I haven't really looked into the GBTX core to get any idea of how difficult it would be to modify for a 4.0 Gbps line rate, and I haven't looked into any other alternative schemes but if you have any time and interest in working in this it would be great :)

**Comment by andrewpeck** [comment]
Error correction is introduced in new trigger link protocol.
