### ISSUE TITLE
Changing OH address table for seamless inclusion into CTP7 one

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/OptoHybridv3#2]
Please remove the <node id="top"> from the address table and let the root node be `<node id="FPGA">`

**Comment by andrewpeck** [comment]
Hi Misha,  Sorry, I'm happy to make changes but I'm not sure what you are requesting (seems like the message got cut short?) 

What do you want the root node be?

**Comment by mexanick** [comment]
oh, just noticed it got short - silly mistake with Markdown formatting. The root node should simply be `<FPGA>`, i.e. you need to remove line 3 and las line.

**Comment by andrewpeck** [comment]
Ok, thanks. fixed in 1422f28297c7c879546e189bd0e59171e0642ddf
