### ISSUE TITLE
Node names mismatch 

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/OptoHybridv3#21]
After the `3.1.5.1C` release the node names for registers `GEM_AMC.OH.OHX.FPGA.TRIG.CNT.VFATY_SBITS` has been changed to 
`GEM_AMC.OH.OHX.FPGA.TRIG.CNT.VFATY`.
Please revert this change

**Comment by andrewpeck** [comment]
Hi Misha,  Yes, this was a typo introduced in the scripts to switch from GE11 <--> GE21, sorry. It is fixed in the code and will be corrected in the next release of the 3.2.X versions that are being tested now
