### ISSUE TITLE
[feature request] uhal compatible address table

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/OptoHybridv3#23]
In order to have the `uhal` address tables dynamically select the appropriate OH version (see evka85/GEM_AMC#39), we need to implement the `FPGA` block in the `uhal_amc_<card>>_link<xx>.xml` file as a `module`, as understood by the `uhal` xml parser.

For this to work, all attributes that are not `uhal` understood (`id`, `address`, `mask`, `permission`, `description`, `mode`, `parameters`, `tags`) should be dropped, and the `FPGA` node should be renamed `top`
This would make most sense to have a parser to dump the uhal address table from the standard address table.

Thus, the new `optohybrid_registers_uhal.xml` would be like:
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- START: GLOBALS DO NOT EDIT -->
<!DOCTYPE node [
<!ENTITY NUM_VFATS_PER_OH "24">
<!ENTITY VFAT_BITMASK  "0xffffff">
]>
<!-- END: GLOBALS DO NOT EDIT -->

<!--  The tags attribute is a free test attribute which meaning is defined by the uHAL user -->
<node id="top">
    <!--Control module -->
    <node id="CONTROL"  address="0x0000"
...
    </node>
</node>
```

Then in the GEM_AMC `uhal`, xml file, we'd have:
```xml
...
<node id="OH" address="0x400000" >
  <node id="OH0" address="0x0" >
    <node id="FPGA" address="0x0" module="file://optohybrid_registers_uhal.xml"/>
    <node id="GEB" address="0x100000">
    ...
  </node>
</node>
...
```

If a rework were in the cards, I'd suggest to parse all of the special FW generating attributes using the [`uhal` supported attributes](https://ipbus.web.cern.ch/ipbus/doc/user/html/software/uhalQuickTutorial.html#what-are-the-tags-and-parameters-attributes), but also understand inertia

**Comment by andrewpeck** [comment]
Firmware has migrated to https://gitlab.cern.ch/emu/0xbefe/ and I am cleaning out my github
