### ISSUE TITLE
Iterating on OH FW Version Registers

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/OptoHybridv3#6]
Follow-up to https://github.com/cms-gem-daq-project/OptoHybridv3/issues/3

In OH FW version 3.0.8.A the FW version is sort of shown as a single register:

```
0x65000004 None         GEM_AMC.OH.OH0.CONTROL.RELEASE
0x65000008 r    GEM_AMC.OH.OH0.CONTROL.RELEASE.DATE                     0x20180207
0x6500000c r    GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION                  0x0300080a
```

However from the SW point of view it would be easier if the OH reported the firmware version identically to how the CTP7 does:

```
0x6640000c r    GEM_AMC.GEM_SYSTEM.RELEASE.MAJOR                        0x00000003
0x6640000c r    GEM_AMC.GEM_SYSTEM.RELEASE.MINOR                        0x00000003
0x6640000c r    GEM_AMC.GEM_SYSTEM.RELEASE.BUILD                        0x00000006
0x66400010 r    GEM_AMC.GEM_SYSTEM.RELEASE.DATE                         0x20180120
```

So for example for v3.0.8.a request that the OH reports:

```
0x65000008 r    GEM_AMC.OH.OH0.CONTROL.RELEASE.DATE                     0x20180207
0x6500000c r    GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION                  0x0300080a
0x6500000c r    GEM_AMC.OH.OH0.CONTROL.RELEASE.MAJOR                     0x00000003
0x6500000c r    GEM_AMC.OH.OH0.CONTROL.RELEASE.MINOR                     0x00000000
0x6500000c r    GEM_AMC.OH.OH0.CONTROL.RELEASE.BUILD                      0x00000008
0x6500000c r    GEM_AMC.OH.OH0.CONTROL.RELEASE.GENERATION          0x0000000a
```

Where for `OHv3b` the `GENERATION` will report `0xb` instead.

This will make getting the FW version and checking for functionality easier in SW (e.g. `CNT.VFATN_SBITS` doesn't exist before FW v3.0.7.a) 

@andrewpeck

**Comment by jsturdy** [comment]
This is likely *just* an address table change

**Comment by bdorney** [comment]
> This is likely just an address table change

Is this a comment to me or to Andrew?  The above was made using the OH v3.0.8.A address table (e.g. most up-to-date)

**Comment by jsturdy** [comment]
E.g., add a sub-node under `GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION`
```
<node id="MAJOR"  address="0x0" mask="0xff000000" permission="r">
<node id="MINOR"  address="0x0" mask="0x00ff0000" permission="r">
<node id="PATCH"  address="0x0" mask="0x0000ff00" permission="r">
<node id="GENERATION"  address="0x0" mask="0x000000ff" permission="r">
```

**Comment by jsturdy** [comment]
You can add this to the address table you have without any input from @andrewpeck and he can/or not implement it similarly
Idealy, this would be implemented similarly to how the `module` attribute was used in the `uhal` based address tables, and the module could be reused wherever this structure is needed

**Comment by andrewpeck** [comment]
Hi Brian, 

I think Jared's point was that this is in principle just a parser change and does not explicitly require changes in the firmware.

In any case, the latest versions of the firmware are updated to match your specifications: 

`
0x65000008 r 	GEM_AMC.OH.OH0.CONTROL.RELEASE.DATE			0x20180214
0x6500000c None 	GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION
0x65000014 r 	GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION.MAJOR		0x00000003
0x65000014 r 	GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION.MINOR		0x00000000
0x65000014 r 	GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION.BUILD		0x00000009
0x65000014 r 	GEM_AMC.OH.OH0.CONTROL.RELEASE.VERSION.GENERATION	0x0000000a
`
