### ISSUE TITLE
Discussion on VFAT Reset Behavior

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/OptoHybridv3#9]
## Brief summary of issue

Discussion started by @andrewpeck via email, migrating it here.  We are discussing the behavior of `GEM_AMC.OH.OH0.FPGA.CONTROL.VFAT.RESET` in the FW and how it could be used.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [X] Discussion

## Proposed Behavior

There is a register that already does a "pulse" reset of the VFATs: `GEM_AMC.OH.OH0.FPGA.GBT.FORCE_RESET_VFATS`.

So I guess writing `0x1` (anything?) to this register causes a pulse reset to be sent to all lines that lasts just one clock cycle so the VFAT's will not be held in hard reset?

@andrewpeck proposes the following (paraphrasing):
> Change the register you have been using, `GEM_AMC.OH.OH0.FPGA.CONTROL.VFAT.RESET`, into a 12 bit mask such that writing `0x1` to the `n^th` bit it asserts and holds that reset line in the hard reset state (voltage high?) until `0x0` is written to that bit.  This gives the functionality to individually reset a given reset line and keep the VFATs on that line in the reset state. Then we keep FORCE_RESET_VFATS as the global reset which is pulsed.

@andrewpeck also mentions supporting that this pulsed reset is part of the `GBT` node because it emulates the different `TTC` commands which can be received from the `GBT`: 

```
eagle60 > readKW GEM_AMC.OH.OH0.FPGA.GBT.FORCE
0x65010014 w GEM_AMC.OH.OH0.FPGA.GBT.FORCE_L1A
0x65010018 w GEM_AMC.OH.OH0.FPGA.GBT.FORCE_BC0
0x6501001c w GEM_AMC.OH.OH0.FPGA.GBT.FORCE_RESYNC
0x65010020 w GEM_AMC.OH.OH0.FPGA.GBT.FORCE_RESET_VFATS
```

## Current Behavior

Right now writing `0x1` to `GEM_AMC.OH.OH0.FPGA.CONTROL.VFAT.RESET` will raise a voltage level and trigger the hard reset for all `vfat3` chips (well reset lines) on the detector.  

The chips will be held in hard reset until `0x0` is written to `GEM_AMC.OH.OH0.FPGA.CONTROL.VFAT.RESET`.

## Context (for feature requests)

Deciding how the hard reset from the OH should be interpreted.

@andrewpeck @evka85 @mexanick @jsturdy

**Comment by jsturdy** [comment]
What exactly is it that is being sussed out here? `TTC` commands (`B-Go`s) are at the same time fixed and configurable
* Fixed, in that there are 16 b-channel transmissions in the TTC stream that may be used
* Configurable in that each subsystem is free to define what any given one of these should mean
  * Typically, we adhere to some convention that `BC0`, `OC0`, `EC0`, `RESYNC`, `HARD_RESET` all have some specific meaning and the rest of them can be defined/requested per subsystem
* Is it that we want a specific request to trigger a `RESET_VFATS` signal and we want this to be separate from the aforementioned "standard" `B-Go`s?
* Coming from the `TTC` stream it would be an incoming command that our electronics would interpret, i.e., no software interaction beyond the configuration of the `iCI` to interpret a certain `B-Go` channel transmission as some specific action our hardware would take
* The software interactions mentioned in the description above may be fine for lab operations, but are incongruous with CMS operations, i.e., if we receive a `TTC` command, it *must* be handled entirely by hardware/firmware, software is either too slow, or unable to trigger the event

**Comment by andrewpeck** [comment]
I'm not sure any of that is relevant for this... the question is just for a "slow" VFAT reset (issued by reg_interface, for example), how do we want to control it.

Currently we write '1', reset line for all VFATs stays high (in reset) until you write '0'

This is just an idea for changing that to have two separate functions: 

1) 12-bit register to control the individual lines (this would be a modification from the current function of this register) 
2) 1-bit "pulsed" register, where writing anything to the register will issue a reset for 1 clock cycle  (this already exists in the OH)

**Comment by bdorney** [comment]
> 12-bit register to control the individual lines (this would be a modification from the current function of this register)
1-bit "pulsed" register, where writing anything to the register will issue a reset for 1 clock cycle (this already exists in the OH)

I think this added behavior will be useful at least from a debugging point of view.

**Comment by andrewpeck** [comment]
VFAT resets are controlled by the SCA going forward so I think this is a moot point by now.
